// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqA4M2ag5ok0HcZoGCjAsFbkQAbEnRFsQ',
    appId: '1:789743203068:web:e35d8170b81a086b835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    authDomain: 'melodic-mania.firebaseapp.com',
    storageBucket: 'melodic-mania.appspot.com',
    measurementId: 'G-51Z95335TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOp6GdjlPmA3R-eA0HuMqRl6bHW3HPVgE',
    appId: '1:789743203068:android:751841bb5a820bb7835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    storageBucket: 'melodic-mania.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUSIMPRLOIwx0Q0ai3dABdjyQx6ddvTQ',
    appId: '1:789743203068:ios:cfa538c5220f852c835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    storageBucket: 'melodic-mania.appspot.com',
    iosBundleId: 'com.example.melodicmania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiUSIMPRLOIwx0Q0ai3dABdjyQx6ddvTQ',
    appId: '1:789743203068:ios:cfa538c5220f852c835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    storageBucket: 'melodic-mania.appspot.com',
    iosBundleId: 'com.example.melodicmania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqA4M2ag5ok0HcZoGCjAsFbkQAbEnRFsQ',
    appId: '1:789743203068:web:03f3a4ad70a571c3835d79',
    messagingSenderId: '789743203068',
    projectId: 'melodic-mania',
    authDomain: 'melodic-mania.firebaseapp.com',
    storageBucket: 'melodic-mania.appspot.com',
    measurementId: 'G-BM8YVVYWRT',
  );
}
